export const menu = [
  { id: 1, name: "Cola", price: 3.0, color: "#FFD580" },
  { id: 2, name: "Fanta", price: 3.0, color: "#FFD580" },
  { id: 3, name: "Sprite", price: 3.0, color: "#FFD580" },
  { id: 4, name: "Ginger Ale", price: 3.5, color: "#FFD580" },
  { id: 5, name: "Tonic", price: 3.5, color: "#FFD580" },
  { id: 6, name: "Spezi", price: 3.5, color: "#FFD580" },
  { id: 7, name: "Kirsche", price: 4.0, color: "#FFD580" },
  { id: 8, name: "Banane", price: 4.0, color: "#FFD580" },
  { id: 9, name: "Kiba", price: 4.0, color: "#FFD580" },
  { id: 10, name: "Apfel", price: 4.0, color: "#FFD580" },
  { id: 11, name: "Birne", price: 4.0, color: "#FFD580" },
  { id: 12, name: "Orange", price: 4.0, color: "#FFD580" },

  { id: 13, name: "Hamburger", price: 7.0, color: "#CBC3E3" },
  { id: 14, name: "Cheeseburger", price: 8.0, color: "#CBC3E3" },
  { id: 15, name: "Doubleburger", price: 9.0, color: "#CBC3E3" },
  { id: 16, name: "Chickenburger", price: 9.0, color: "#CBC3E3" },
  { id: 17, name: "Baconburger", price: 9.5, color: "#CBC3E3" },
  { id: 18, name: "Veggiburger", price: 9.5, color: "#CBC3E3" },
  { id: 19, name: "Gigaburger", price: 10.0, color: "#CBC3E3" },
  { id: 20, name: "Pommes", price: 4.0, color: "#CBC3E3" },
];
